$kind: http-request
name: Create a task
url: "{{api_url}}/tasks"
method: POST
body:
  type: json
  content: |-
    {
        "name": "Mock data và test postman",
        "projectId": "1c28d4b9-25e4-4da4-93ad-33314637cd9d",
        "sprintId": "c42eb789-111a-4b97-b77c-b62587f058e6",
        "parentTaskId": "8DD5602C-EB76-4E72-BFF4-707011B0E6AF",
        "dueDate": "2026-07-31",
        "priority": 2
    }
auth:
  type: bearer
  credentials:
    token: "{{access_token}}"
order: 1785383901548
