$kind: http-request
name: Move to Sprint
url: "{{api_url}}/tasks/:id/sprint"
method: PUT
pathVariables:
  - key: id
    value: 8DD5602C-EB76-4E72-BFF4-707011B0E6AF
    description: ""
    $type: |-
      {
        "type": "object",
        "properties": {
          "value": {
            "type": "string",
            "format": "uuid"
          }
        },
        "required": [
          "value"
        ]
      }
body:
  type: json
  content: |-
    {
        "sprintId": null
    }
auth:
  type: bearer
  credentials:
    token: "{{access_token}}"
order: 4502220725651033
