$kind: http-request
name: Unassign (By self or by PM)
url: "{{api_url}}/tasks/:id/assignees/:employeeId"
method: DELETE
pathVariables:
  - key: id
    value: ""
    description: ""
    $type: |-
      {
        "type": "object",
        "properties": {
          "value": {
            "type": "string",
            "format": "uuid"
          }
        },
        "required": [
          "value"
        ]
      }
  - key: employeeId
    value: ""
    description: ""
    $type: |-
      {
        "type": "object",
        "properties": {
          "value": {
            "type": "string",
            "format": "uuid"
          }
        },
        "required": [
          "value"
        ]
      }
order: 4503599339761701
